# [AWS DynamoDB Local](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html)
aws:
  region: us-east-1
  dynamodb:
    endpoint: http://localhost:4566
    table:
      users: Users
      tokens: Tokens
  secret:
    access-key: test
    key-id: test

server:
  port: 9801

jwt:
  secret: "wN!as4kdpN98A2m3V9x7QqZLrP0f98A2m3V9x7QqZLGtYz"  # debe tener al menos 32 caracteres (256 bits)